name: Run workflow tests as an action within PR's
'on': pull_request
jobs: 
  test_workflows:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup data dir
        run: echo "need command for downloading barski-lab data dir"

      - name: run tests in docker container
        run: echo "probable command will be; bash run_test_docker.sh"
   